FROM node:iron-alpine3.21 AS build

# Specify working directory other than / - default directory to run commands
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
