# Pin specific version
# Use slim for reduced image size
FROM node:iron-alpine3.21

# Specify working directory other than /
WORKDIR /usr/src/app

COPY . .

RUN npm install

CMD [ "node", "index.js" ]
